setting : blue-green 배포 github action 설정

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -59,8 +59,76 @@ jobs:
           username: ${{ secrets.SERVER_USERNAME }}
           key: ${{ secrets.SERVER_SSH_KEY }}
           script: |
-            sudo docker stop prod || true
-            sudo docker rm prod || true
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
-            sudo docker run --name prod -d -p ${{ secrets.PORT_MAPPING }} ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
+            
+            IS_GREEN=$(docker ps | grep prod-green)
+            echo $IS_GREEN
+
+            max_count=10
+            count=0
+            check=1
+          
+            if [ -z $IS_GREEN ]; then
+              echo "## BLUE => GREEN ###"
+              echo "1. green container up"
+              sudo docker run --name prod-green -d -p ${{ secrets.GREEN_PORT }}:${{ secrets.CONTAINER_PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
+
+              while [ $count -lt $max_count ]; do
+                echo "2. green health check...  ($count)"
+                count=$((count + 1))
+                sleep 20
+            
+                REQUEST=$(curl "http://${{ secrets.SERVER_IP }}:${{ secrets.GREEN_PORT }}")
+                if [ -n "$REQUEST" ]; then
+                  echo "health check success"
+                  check=0
+            
+                  echo "3. reload nginx"
+                  sudo systemctl reload nginx
+
+                  echo "4. blue container down"
+                  sudo docker stop prod-blue || true
+                  sudo docker rm prod-blue || true
+                  break;
+                fi
+              done;
+              if [ $check = 1 ]; then
+                echo "3. health check fail"
+                sudo docker stop prod-green || true
+                sudo docker rm prod-green || true
+              fi  
+            
+            else
+              echo "## GREEN => BLUE ###"
+              echo "1. blue container up"
+              sudo docker run --name prod-blue -d -p ${{ secrets.BLUE_PORT }}:${{ secrets.CONTAINER_PORT }} ${{ secrets.DOCKERHUB_USERNAME }}/neuroflow
+
+              count=0
+              while [ $count -lt $max_count ]; do
+                echo "2. blue health check... ($count)"
+                count=$((count + 1))
+                sleep 20
+            
+                REQUEST=$(curl "http://${{ secrets.SERVER_IP }}:${{ secrets.BLUE_PORT }}")
+                if [ -n "$REQUEST" ]; then
+                  echo "health check success"
+                  check=0
+
+                  echo "3. reload nginx"
+                  sudo systemctl reload nginx
+
+                  echo "4. green container down"
+                  sudo docker stop prod-green || true
+                  sudo docker rm prod-green || true
+                  break;
+                fi
+              done;
+            
+              if [ $check = 1 ]; then
+                echo "3. health check fail"
+                sudo docker stop prod-blue || true
+                sudo docker rm prod-blue ||true
+              fi
+            fi
+            
             sudo docker system prune -f
